# Generated by Django 5.2 on 2025-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], max_length=50),
        ),
    ]
